### ISSUE TITLE
[Suggestion]readme more friendly?

### ISSUE THREAD

**Issue by neon-izm** [hecomi/create-upm-branch-action#1]
When using this workflow, Actions in the repository must have Write permission.
It may be helpful to mention this in the Readme.

settings/actions/General

![image](https://github.com/hecomi/create-upm-branch-action/assets/3115650/a8300f20-8d50-4a93-8285-973e4121160b)

**Comment by hecomi** [comment]
Thank you for pointing out the need to mention Write permissions in the README. I've updated it accordingly (I've also updated the instruction to publish the repository to npm). Your input is much appreciated!
